version: '3'
services:
  postgres:
    image: 'postgres:14.4-alpine'
    volumes:
      - '~/docker/volumes/note_keeper/test/postgresql:/var/lib/postgresql/data'
    # Database name, user name, user password are taken from those environment variables.
    # Database is created there and no need to run rails db:create.
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=note_keeper_test
      - POSTGRES_USER=note_keeper_test
      - POSTGRES_PASSWORD=note_keeper_test
    hostname: 'postgres'
    expose:
      - '5432'
    ports:
      - '5432:5432'

  note_keeper_app:
    build:
      dockerfile: Dockerfile.test
      context: ./
    volumes:
      - '/note_keeper_app/node_modules'
      - './:/note_keeper_app'
    environment:
      - RAILS_ENV=test
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=note_keeper_test
      - POSTGRES_USER=note_keeper_test
      - POSTGRES_PASSWORD=note_keeper_test
    hostname: 'note_keeper_app'
    expose:
      - '3000'
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    restart: on-failure
    # Feature tests which are performed by rspec + selenium web driver are excluded, because they need rails app to be running"
    command: sh -c '. ~/.bashrc && rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rspec --format documentation --exclude-pattern "**/features/*_spec.rb" | tee -a ./log/rspec-test.log'
